# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db226fd54f340b84d6e7cdbd72723dc35f44c91e0ca0658addd67cb7c4463f56243ca05e466f3ce227bc432d88c5b254a89804ef63636da8dba793c71ad7c35f

test:
  secret_key_base: 2ee5b383b4c0b580fe9818e2dbe049a912e13c9cbc9fe4127b8af454f1408a71e9321aa80edb23fbc1cacf9bd45a80fd6980407884e65d8740497158d0f87398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
